import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import Script from "next/script";
import Providers from "./components/Providers";
const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"], // Subsets you need
  weight: ["400", "500", "700"], // Font weights you want
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetBrainsMono.className} antialiased`}>
        <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="lazyOnload"/>
          <Providers>
            {children}
          </Providers>
      </body>
    </html>
  );
}
